server:
  port: 8081


dubbo:
  application:
    name: consumer

  monitor:
    protocol: registry #连接监控中心

  protocol:
    name: dubbo
    port: 20880

  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper